/**
 * avoxel284 2026
 ************************************
 * Refactored from https://github.com/rezoner/playground
 * Originally written by Rezoner.
 */

import type Application from "./Application";
import Events from "./Events";

/**
 * Keyboard related functionality.
 *
 * A key name is computed by either taking the ASCII representation or
 * using the `keycodes` array to assign a name. To get corresponding code
 * use `original.which` in event handler.
 *
 * Properties:
 * - keys: associative array that maps key names to either true or false
 *   if a key is not in this array it was never pressed
 * - preventDefault: stop event propagation
 * - bypassKeys: `preventDefault` will not act on these keys
 * - keydownEvent: caches information about last key down event
 *     - key: name of the key
 *     - original: original event
 * - keyupEvent: caches information about last key up event
 *     - key: name of the key
 *     - original: original event
 *
 * Events generated by this object:
 * - keydown: a key was pressed (handler receives `keydownEvent` object)
 * - keyup: a key was released (handler receives `keyupEvent` object)
 *
 * Reference: http://playgroundjs.com/playground-keyboard
 */
class Keyboard extends Events {
	app: Application;
	keys = {};
	timestamps = {};
	any = false;
	lastKey = -1;
	enabled = true;

	constructor(app: Application) {
		super();
		this.app = app;

		document.addEventListener("keydown", (event: KeyboardEvent) => {
			if (!this.enabled) return;

			if (event.which >= 48 && event.which <= 90)
				var keyName = String.fromCharCode(event.which).toLowerCase();
			else var keyName = this.keycodes[event.which];

			if (this.mapping[keyName]) keyName = this.mapping[keyName];

			if (this.keys[keyName]) return;

			this.any++;

			this.keydownEvent.key = keyName;
			this.keydownEvent.original = event;

			this.keys[keyName] = true;

			if (
				keyName === this.lastKey &&
				Date.now() - this.timestamps[keyName] < this.doubleTimeframe * 1000
			) {
				this.timestamps[keyName] = Date.now() - this.doubleTimeframe;
				this.keydownEvent.double = true;
			} else {
				this.timestamps[keyName] = Date.now();
				this.keydownEvent.double = false;
			}

			this.trigger("keydown", this.keydownEvent);

			if (this.preventDefault && document.activeElement === document.body) {
				var bypass = event.metaKey;

				if (!bypass) {
					for (var i = 0; i < this.bypassKeys.length; i++) {
						if (this.keys[this.bypassKeys[i]]) {
							bypass = true;
							break;
						}
					}
				}

				if (!bypass) {
					// e.returnValue = false;
					// e.keyCode = 0;
					event.preventDefault();
					event.stopPropagation();
				}
			}

			this.lastKey = keyName;
		});
	}
}

export default Keyboard;
