/**
 * avoxel284 2026
 ************************************
 * Refactored from https://github.com/rezoner/playground
 * Originally written by Rezoner.
 */

import type Application from "./Application";
import Events from "./Events";
import { classInParents } from "./Util";

/**
 * Touch related functionality.
 *
 * The object keeps track of active touches using an unique id
 * provided by the browser. When a touch starts an entry is added
 * to the `touches` associative array with the key being the
 * unique identifier and the value an object with following members:
 * - x: horizontal position in pixels/scale
 * - y: vertical position in pixels/scale
 *
 * When the tracking point changes location the values are updated and
 * when the touches ends the entry is removed from the `touches` array.
 *
 * Properties:
 * - app: the main application object
 * - element: the DOM element we're handling events for
 * - touches: list of active touches
 * - x, y: last changed position across all touches
 *
 * Events generated by this object:
 * - touchmove: a touch changed its position
 * - touchstart: a touch was added
 * - touchend: a touch ended
 *
 * Event handlers receive the position (x, y), the id (identifier) and
 * original event.
 *
 * Reference: http://playgroundjs.com/playground-touch
 */

export interface PlaygroundTouchEventData {
	x: number;
	y: number;
	original: globalThis.Touch;
	id: number;
}

class Touch extends Events {
	app: Application;
	element: HTMLElement;
	touches: { [id: number]: { x: number; y: number } } = {};
	enabled = true;
	x = 0;
	y = 0;
	elementOffset = { x: 0, y: 0 };

	constructor(app: Application) {
		super();
		this.app = app;
		this.element = app.container;

		this.element.addEventListener("touchmove", this.handleTouchMove, { passive: false });
		this.element.addEventListener("touchstart", this.handleTouchStart, { passive: false });
		this.element.addEventListener("touchend", this.handleTouchEnd, { passive: false });
	}

	handleTouchMove(event: TouchEvent) {
		if (!this.enabled) return;

		for (let i = 0; i < event.changedTouches.length; i++) {
			let touch = event.changedTouches[i];

			let touchMoveData: PlaygroundTouchEventData = {
				x: ((touch.pageX - this.elementOffset.x - this.app.offsetX) / this.app.scale) | 0,
				y: ((touch.pageY - this.elementOffset.y - this.app.offsetY) / this.app.scale) | 0,
				original: touch,
				id: touch.identifier,
			};

			this.x = touchMoveData.x;
			this.y = touchMoveData.y;
			this.touches[touch.identifier] = { x: touchMoveData.x, y: touchMoveData.y };

			this.emit("touchmove", touchMoveData);
		}

		if (!classInParents(event.target, "ui")) event.preventDefault();
	}

	handleTouchStart(event: TouchEvent) {
		if (!this.enabled) return;

		for (let i = 0; i < event.changedTouches.length; i++) {
			let touch = event.changedTouches[i];

			let touchStartData: PlaygroundTouchEventData = {
				x: ((touch.pageX - this.elementOffset.x - this.app.offsetX) / this.app.scale) | 0,
				y: ((touch.pageY - this.elementOffset.y - this.app.offsetY) / this.app.scale) | 0,
				original: touch,
				id: touch.identifier,
			};

			this.x = touchStartData.x;
			this.y = touchStartData.y;
			this.touches[touch.identifier] = { x: touchStartData.x, y: touchStartData.y };

			this.emit("touchstart", touchStartData);
		}

		if (!classInParents(event.target, "ui")) event.preventDefault();
	}

	handleTouchEnd(event: TouchEvent) {
		if (!this.enabled) return;

		for (let i = 0; i < event.changedTouches.length; i++) {
			let touch = event.changedTouches[i];

			let touchEndData: PlaygroundTouchEventData = {
				x: ((touch.pageX - this.elementOffset.x - this.app.offsetX) / this.app.scale) | 0,
				y: ((touch.pageY - this.elementOffset.y - this.app.offsetY) / this.app.scale) | 0,
				original: touch,
				id: touch.identifier,
			};

			this.x = touchEndData.x;
			this.y = touchEndData.y;
			this.touches[touch.identifier] = { x: touchEndData.x, y: touchEndData.y };

			this.emit("touchend", touchEndData);
		}

		if (!classInParents(event.target, "ui")) event.preventDefault();
	}

	handleResize() {
		this.elementOffset = this.getElementOffset();
	}

	getElementOffset() {
		let offsetX = 0;
		let offsetY = 0;
		let el: any;

		do {
			offsetX += this.element.offsetLeft;
			offsetY += this.element.offsetTop;
		} while ((el = this.element.offsetParent));

		return {
			x: offsetX,
			y: offsetY,
		};
	}
}

export default Touch;
